{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.Version -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "odoo-doodba.fullname" . }}
  labels:
{{ include "odoo-doodba.labels" . | indent 4 }}
  annotations:
  {{- if .Values.ingress.recommendedNginxSettings }}
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-body-size: "2000m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1500"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1500"
    nginx.ingress.kubernetes.io/gzip-types: "application/atom+xml application/javascript application/x-javascript application/json application/rss+xml application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/svg+xml image/x-icon text/css text/xml text/plain text/x-component text/less"
  {{- end }}
  {{ if .Values.ingress.wwwRedirect }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  {{ end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ $.Values.service.geventPath }}
            {{ if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.Version }}
            pathType: Prefix
            {{ end }}
            backend:
            {{ if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.Version }}
              service:
                name: {{ include "odoo-doodba.fullname" $ }}
                port:
                  number: {{ $.Values.service.geventPort }}
            {{ else }}
              serviceName: {{ include "odoo-doodba.fullname" $ }}
              servicePort: {{ $.Values.service.geventPort }}
            {{ end }}
          - path: /
            {{ if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.Version }}
            pathType: Prefix
            {{ end }}
            backend:
            {{ if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.Version }}
              service:
                name: {{ include "odoo-doodba.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
            {{ else }}
              serviceName: {{ include "odoo-doodba.fullname" $ }}
              servicePort: {{ $.Values.service.port }}
            {{ end }}
  {{- end }}
{{- end }}
