apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo-doodba.fullname" . }}
  {{ if .Values.service.annotations }}
  annotations:
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{ end }}
  labels:
{{ include "odoo-doodba.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8069
      name: http
    - port: {{ .Values.service.geventPort }}
      targetPort: 8072
      name: gevent
  selector:
    app.kubernetes.io/name: {{ include "odoo-doodba.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}